apiVersion: apps/v1
kind: Deployment

metadata:
  name: irsa-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: irsa-demo

  template:
    metadata:
      labels:
        app: irsa-demo

    spec:
      serviceAccountName: dynamodb-sa

      containers:
      - name: app
        image: YOUR_ECR_IMAGE
        imagePullPolicy: Always