apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secret.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}