apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb-app
  template:
    metadata:
      labels:
        app: dynamodb-app
    spec:
      serviceAccountName: dynamodb-sa
      containers:
      - name: dynamodb-app
        image: 262504053817.dkr.ecr.us-east-1.amazonaws.com/dynamodb-app:latest
        ports:
        - containerPort: 5000